### ISSUE TITLE
climate only works one way

### ISSUE THREAD

**Issue by dingausmwald** [RogerSelwyn/mqtt_discoverystream_ha#1]
Hey, congrats, your first issue.

I posted in the main repository, but seems you did not read this. I tried your fork but climate only works one way. (states change, but i cant change from my second system) I get this

`Template variable warning: 'dict object' has no attribute 'hvac_action' when rendering '{{ value_json.hvac_action }}'`

is it because i am using the bosch integration for my climate devices or is it a bug in your code actually?

**Comment by RogerSelwyn** [comment]
Sorry, didn't see this until now. I've only written it one day so far. I'll take a look at what it would take to make it two way.

**Comment by RogerSelwyn** [comment]
Also, I noticed a problem that may be attributed to the error you have there, so have made some changes in the last couple of versions.

**Comment by dingausmwald** [comment]
Thank you. Its working. My bosch thermostats just support on/off, automatic mode(?) and set temperature. Anyway, all good.

**Comment by RogerSelwyn** [comment]
If you can screenshot me the state from developer tab, and the controls available, I'll see if I can add them tomorrow. Automatic mode doesn't mean anything to me, but I maybe able to make sense if I see what you have.

**Comment by dingausmwald** [comment]
![image](https://user-images.githubusercontent.com/30699246/210626184-54d02313-af19-40c8-937b-e80986339baa.png)

nothing to fancy, its hvac_mode, it does work. Nothing to do here. Thanks again

**Comment by RogerSelwyn** [comment]
Yep, those should work. If you have a separate turn on/off let me know.

**Comment by dingausmwald** [comment]
ah, one thing: the steps are not 0,5. I can just change 1C°.

**Comment by RogerSelwyn** [comment]
Ok, I'll look at that. I didn't set the step, it defaulted it and I don't think there is a value for me to replicate. Can you do me a similar screenshot from your sending system?

**Comment by dingausmwald** [comment]
![image](https://user-images.githubusercontent.com/30699246/210627157-bff6f40f-4190-43d1-9afa-2dc2151a691d.png)

**Comment by RogerSelwyn** [comment]
Ok, I can replicate that. I can see my Nest supports 0.5, but doesn't show it as a state. I'll see what the default is and set it to that.

**Comment by dingausmwald** [comment]
a warning is spamming my logs after setting an automation on the receiving system for the climate device with:

```
service: climate.set_temperature
data:
  temperature: "{{state_attr('climate.heizung_badezimmer', 'temperature') | float(0) +1}}"
target:
  device_id: 0acd42dc270efbf3ad64fb99a014dde6
```

`'"none"' received on topic homeassistant/climate/heizung_badezimmer/preset_mode. '"none"' is not a valid preset mode`

**Comment by RogerSelwyn** [comment]
Please provide the whole log message so I can see what is issuing the message.

**Comment by dingausmwald** [comment]
```
Logger: homeassistant.components.mqtt.climate
Source: components/mqtt/climate.py:701
Integration: MQTT ([documentation](https://www.home-assistant.io/integrations/mqtt), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+mqtt%22))
First occurred: 07:20:00 (43 occurrences)
Last logged: 08:54:27

'"none"' received on topic homeassistant/climate/heizung_badezimmer/preset_mode. '"none"' is not a valid preset mode
```

**Comment by RogerSelwyn** [comment]
I don't think the automation you have there will do that. But it looks like the none value has extra quotes on it. Have you got mqttexplorer and can see what it is actually sending? For me when sending 'none' from nest device, it has no quotes at all.

**Comment by RogerSelwyn** [comment]
Also, I assume this is a custom integration, can you provide me aa link to the GitHub.

**Comment by RogerSelwyn** [comment]
And probably finally, if you. set it to a different preset mode, do you get the same error?

**Comment by dingausmwald** [comment]
https://github.com/tschamm/boschshc-hass

![image](https://user-images.githubusercontent.com/30699246/210736426-568143e6-3d32-44f0-a9dd-4fd8b8dcac35.png)

**Comment by dingausmwald** [comment]
it sends "none" and none alternately. Strange.
![image](https://user-images.githubusercontent.com/30699246/210736708-192f5691-48b8-45c0-8d75-7f4f9564810d.png)

**Comment by RogerSelwyn** [comment]
Need to have a look why it is doing that. MQTT Discovery Stream just sends what it receives. If it just started, check if your automation is doing something weird, but doesn't look like it is touching it.

**Comment by RogerSelwyn** [comment]
I'm having an mqtt nightmare. My dev environment went tits up, I think because something change in VSCode. Now none of my subscriptions are working. I think I'm giving up for the day.

**Comment by RogerSelwyn** [comment]
> ah, one thing: the steps are not 0,5. I can just change 1C°.

Should be fixed with https://github.com/RogerSelwyn/mqtt_discoverystream_ha/releases/tag/v0.10.6. Default to 0.5, or whatever source is configured to.

I've also included the code above.

Finally, I've added an option to break out the response commands, because I was getting in a loop across my mqtt bridge.

**Comment by RogerSelwyn** [comment]
If you can confirm vetting is working for you, I’ll close the issue.

**Comment by dingausmwald** [comment]
Hey there,

i did the change in climate.py , but now something really strange happens here. The warning on the receiving system didn't change, but on the sending system those warnings popped up

`Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:980
Integration: Sensor
First occurred: 10:01:56 (118 occurrences)
Last logged: 10:02:31

Entity sensor.boxen_energy_factor (<class 'homeassistant.components.tasmota.sensor.TasmotaSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power_factor') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+tasmota%22
Entity sensor.fensterlampen_energy_factor (<class 'homeassistant.components.tasmota.sensor.TasmotaSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power_factor') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+tasmota%22
Entity sensor.fernseher_schlafzimmer_energy_factor (<class 'homeassistant.components.tasmota.sensor.TasmotaSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power_factor') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+tasmota%22
Entity sensor.stehlampen_energy_factor (<class 'homeassistant.components.tasmota.sensor.TasmotaSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power_factor') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+tasmota%22
Entity sensor.waschmaschine_energy_factor (<class 'homeassistant.components.tasmota.sensor.TasmotaSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('power_factor') it is using; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+tasmota%22`

this is strange because those devices are not even climate related nor are they exposed to the receiving system.

**Comment by RogerSelwyn** [comment]
Not sure what you mean now about the change in climate.py since the latest release had all changes in just use that.

I suspect that your errors are from a 2023.1 upgrade. Nothing to do with mqtt. I can’t help beyond that I’m afraid.

**Comment by dingausmwald** [comment]
> Try changing the functions in /classes/climate.py at around line 73 to be like this. To be honest:
> 
> ```
>     async def async_publish_state(self, new_state, mybase):
>         """Publish the state for a light."""
>         await self._async_publish_attribute(new_state, mybase, ATTR_HVAC_ACTION, True)
>         await self._async_publish_attribute(new_state, mybase, ATTR_CURRENT_TEMPERATURE)
>         await self._async_publish_attribute(new_state, mybase, ATTR_PRESET_MODE, True)
>         await self._async_publish_attribute(new_state, mybase, ATTR_TEMPERATURE)
> 
>         await async_publish_base_attributes(self._hass, new_state, mybase)
> 
>         payload = new_state.state
>         if payload == STATE_UNAVAILABLE:
>             payload = STATE_OFF
>         await mqtt.async_publish(
>             self._hass, f"{mybase}{ATTR_HVAC_MODE}", payload, 1, True
>         )
> 
>     async def _async_publish_attribute(
>         self, new_state, mybase, attribute_name, strip=False
>     ):
>         if attribute_name in new_state.attributes:
>             value = new_state.attributes[attribute_name]
>             if strip:
>                 value = value.strip('"')
>             await mqtt.async_publish(
>                 self._hass,
>                 f"{mybase}{attribute_name}",
>                 value,
>                 1,
>                 True,
>             )
> ```

i mean this. This definitely isn't in 0.10.6. But maybe you're right with the 2023 update. Anyway, the logs saying "none" and so on are still there.

**Comment by RogerSelwyn** [comment]
This is the code from v0.10.6, starting at line 79, slight change at line 100 from what I posted previously which you have probably removed with pasting in the previously posted code.

```
    async def async_publish_state(self, new_state, mybase):
        """Publish the state for a light."""
        await self._async_publish_attribute(new_state, mybase, ATTR_HVAC_ACTION, True)
        await self._async_publish_attribute(new_state, mybase, ATTR_CURRENT_TEMPERATURE)
        await self._async_publish_attribute(new_state, mybase, ATTR_PRESET_MODE, True)
        await self._async_publish_attribute(new_state, mybase, ATTR_TEMPERATURE)

        await async_publish_base_attributes(self._hass, new_state, mybase)

        payload = new_state.state
        if payload == STATE_UNAVAILABLE:
            payload = STATE_OFF
        await mqtt.async_publish(
            self._hass, f"{mybase}{ATTR_HVAC_MODE}", payload, 1, True
        )

    async def _async_publish_attribute(
        self, new_state, mybase, attribute_name, strip=False
    ):
        if attribute_name in new_state.attributes:
            value = new_state.attributes[attribute_name]
            if value and strip:
                value = value.strip('"')
            await mqtt.async_publish(
                self._hass,
                f"{mybase}{attribute_name}",
                value,
                1,
                True,
            )
```

Please add this line straight after the comment in async_publish_state
`        _LOGGER.debug("New State %s;", new_state)`

```
    async def async_publish_state(self, new_state, mybase):
        """Publish the state for a light."""
        _LOGGER.debug("New State %s;", new_state)
        await self._async_publish_attribute(new_state, mybase, ATTR_HVAC_ACTION, True)
```

**Comment by RogerSelwyn** [comment]
If you can then post back your log with debug messages and the errors you are getting so I can see which state change is triggering the error. I suspect that is the logs on both servers, so hoping the time is in sync across the servers.

**Comment by RogerSelwyn** [comment]
No further input, so closing.
