### ISSUE TITLE
Issue with dimmers , brightness "0"

### ISSUE THREAD

**Issue by pergolafabio** [RogerSelwyn/mqtt_discoverystream_ha#34]
Hey, setting up and testing now dimmers, is it possible this component it maybe wrong in case of dimmers?

should the state not be like:

`{ "state": "OFF",  "brightness": 0, }`
instead of:
`{  "state": "OFF" }`

I'm setting up an dimmer mqtt, below is the code:

```
        Type switch : dimmer1 "Eethoek Raam" 		[ stateTopic="openhab/light/dimmer1/state", 
														commandTopic="openhab/light/dimmer1/set_light", 
														transformationPattern="JSONPATH:$.state", 
														formatBeforePublish="{\"state\":\"%s\"}", 
														on="ON", 
														off="OFF" ]
		Type dimmer : dimmer1b "Eethoek Raam"        [ stateTopic="openhab/light/dimmer1/state",
														commandTopic="openhab/light/dimmer1/set_light", 
														transformationPattern="JSONPATH:$.brightness", 
														formatBeforePublish="{\"brightness\":%s}",
														min=0, max=255, step=10]
```

the second type is incorrect and i dont know how to resolve it, it works when the light is ON and where there is a value between 1 and 255..., but when i turn OFF the light, STATE = OFF , it doesnt provide the brightness in the JSON, and then i get error:

`Executing the JSONPATH-transformation failed: Invalid path '$.brightness' in '{"state": "OFF"}'. Pattern: '$.brightness'. Value: '{"state": "OFF"}'`

or can you help me how to resolve it?

**Comment by RogerSelwyn** [comment]
I'm not quite sure why you would need to set the brightness to 0 when you are turning it off. I'm pretty sure HA doesn't send that information as part of the event when a light is switched off.

> ```
>         Type switch : dimmer1 "Eethoek Raam" 		[ stateTopic="openhab/light/dimmer1/state", 
> 														commandTopic="openhab/light/dimmer1/set_light", 
> 														transformationPattern="JSONPATH:$.state", 
> 														formatBeforePublish="{\"state\":\"%s\"}", 
> 														on="ON", 
> 														off="OFF" ]
> 		Type dimmer : dimmer1b "Eethoek Raam"        [ stateTopic="openhab/light/dimmer1/state",
> 														commandTopic="openhab/light/dimmer1/set_light", 
> 														transformationPattern="JSONPATH:$.brightness", 
> 														formatBeforePublish="{\"brightness\":%s}",
> 														min=0, max=255, step=10]

I don't recognise these, they are created by DiscoveryStream, not sure where you are entering them in HA. If you are trying to send lights into HA from elsewhere, then your reference for discovery messages for lights is this - https://www.home-assistant.io/integrations/light.mqtt/. You can see an MQTT example of a discovery topic (rather than JSON) by looking at a discovery message send from DiscoveryStream on MQTT Explorer.

**Comment by RogerSelwyn** [comment]
Confirmed, Brightness is not sent by HA in the state change message for a change to Off

**Comment by pergolafabio** [comment]
ok, no problem, i can figure it out with an javascript , its ok!
