### ISSUE TITLE
Duplicates ..

### ISSUE THREAD

**Issue by pergolafabio** [RogerSelwyn/mqtt_discoverystream_ha#35]
Hey, i'm aware of the duplicates, so i use another basetopic , like below

```
mqtt_discoverystream_alt:
  base_topic: openhab
  publish_attributes: true
  publish_timestamps: false
  publish_discovery: true
  include:
    domains:
      #- light
      - switch
      - cover
      - input_select
      - input_text
```

i have now commented out lights, since they are duplicating themself? in log i see for example:
```

2024-10-29 18:32:30.554 ERROR (MainThread) [homeassistant.core] Error running job: <Job listen homeassistant_start HassJobType.Callback <function _async_setup_entity_restore.<locals>._write_unavailable_states at 0x7f2cfb823ce0>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1562, in async_fire_internal
    self._hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 937, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1608, in _write_unavailable_states
    entry.write_unavailable_state(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 394, in write_unavailable_state
    hass.states.async_set(self.entity_id, STATE_UNAVAILABLE, attrs)
  File "/usr/src/homeassistant/homeassistant/core.py", line 2244, in async_set
    self.async_set_internal(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2332, in async_set_internal
    state = State(
            ^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1771, in __init__
    raise InvalidEntityFormatError(
homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: light.dimmer2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2__10. Format should be <domain>.<object_id>

```

![image](https://github.com/user-attachments/assets/f7878026-42a6-4253-af1a-31c8af87076a)

what could be the culprit?

**Comment by RogerSelwyn** [comment]
How do you have your HA MQTT integration configured? Looks like you are looping it.

**Comment by pergolafabio** [comment]
yea, but i think its because they are already now created in HA itself, i need to delete them there as well :-(

![image](https://github.com/user-attachments/assets/7a3e2e7d-55de-4fcc-af33-e0ee9628a4f3)

**Comment by RogerSelwyn** [comment]
You can send an empty message to the discovery topic location and it will delete itself

**Comment by pergolafabio** [comment]
also the orphaned entities? its like 6000 of them :-)

**Comment by RogerSelwyn** [comment]
Or if they were created by mqtt, which I assume they were, just reboot ha and as long as you haven’t retained them on the broke they won’t get recreated.

**Comment by pergolafabio** [comment]
yeah, i delete everything in mqtt , but they are not deleted by itself in HA after reboot :-(

tbut seems there is an "hacs"  integration "spook" , to delete them all at once ...

**Comment by RogerSelwyn** [comment]
Refresh your browser cache.

**Comment by pergolafabio** [comment]
they are still there, even after the service , this file is populated with them  :core.entity_registry

gonna remove it from there

**Comment by pergolafabio** [comment]
crap, even if i delete them from this file, they are just back :-(

![image](https://github.com/user-attachments/assets/1ba12e79-1563-4a37-8583-30c3fe9a2654)

**Comment by RogerSelwyn** [comment]
Are they on your broker? You can check what is being created at boot by looking at the MQTT Integration information.

**Comment by pergolafabio** [comment]
no, they are not on the broker, i deleted it there, stopped also your intergation
in the file they are still there, but not visible in HA itself

 :-(

**Comment by RogerSelwyn** [comment]
Give HA a chance to process, it runs cleanup processes on a schedule.

**Comment by pergolafabio** [comment]
ok, otherwise i restore a backup

**Comment by RogerSelwyn** [comment]
> Hey, i'm aware of the duplicates, so i use another basetopic , like below
> 
> ```
> mqtt_discoverystream_alt:
>   base_topic: openhab
>   publish_attributes: true
>   publish_timestamps: false
>   publish_discovery: true
>   include:
>     domains:
>       #- light
>       - switch
>       - cover
>       - input_select
>       - input_text
> ```
> 
> i have now commented out lights, since they are duplicating themself? in log i see for example:
> 
> ```
> 
> 2024-10-29 18:32:30.554 ERROR (MainThread) [homeassistant.core] Error running job: <Job listen homeassistant_start HassJobType.Callback <function _async_setup_entity_restore.<locals>._write_unavailable_states at 0x7f2cfb823ce0>>
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1562, in async_fire_internal
>     self._hass.async_run_hass_job(job, event)
>   File "/usr/src/homeassistant/homeassistant/core.py", line 937, in async_run_hass_job
>     hassjob.target(*args)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 1608, in _write_unavailable_states
>     entry.write_unavailable_state(hass)
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 394, in write_unavailable_state
>     hass.states.async_set(self.entity_id, STATE_UNAVAILABLE, attrs)
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2244, in async_set
>     self.async_set_internal(
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2332, in async_set_internal
>     state = State(
>             ^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 1771, in __init__
>     raise InvalidEntityFormatError(
> homeassistant.exceptions.InvalidEntityFormatError: Invalid entity id encountered: light.dimmer2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2_2__10. Format should be <domain>.<object_id>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/43251136/381246680-f7878026-42a6-4253-af1a-31c8af87076a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMjU5NjUsIm5iZiI6MTczMDIyNTY2NSwicGF0aCI6Ii80MzI1MTEzNi8zODEyNDY2ODAtZjc4NzgwMjYtNDJhNi00MjUzLWFmMWEtMzFjOGFmODcwNzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE4MTQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZTFmMDA3Y2QxMjA3MGFjNjhlMTk4OTIwZTZiYzhmNDViN2ZmNGU3MjM3OTlmNWQ1MzJjMDRkNzRmYWI1NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Nr9R-UElzoTQUukoXUqtkQtXva9hMilVOUEs0BUWOjQ)
> 
> what could be the culprit?

This will happen if you do not separate the discovery topic from the topic used by the HA MQTT integration. So you would very unlikely to ever configure discovery+topic to home assistant because that is what the HA MQTT integration uses by default. 

This is especially true when you are publishing whole domains, rather than individual entities. The MQTT Discovery Stream does not ignore entities created via the MQTT Integration, because there may be a good reason why you want to publish.

**Comment by pergolafabio** [comment]
ok, they are in a section, deleted entities
so will  be OK  later i guess :-)

![image](https://github.com/user-attachments/assets/d77e1073-95c5-4f7e-86bb-b73d943e4b25)

**Comment by pergolafabio** [comment]
restored from snapshot this morning, all good :-)
