### ISSUE TITLE
Feature: Add support for input_* entities

### ISSUE THREAD

**Issue by RogerSelwyn** [RogerSelwyn/mqtt_discoverystream_ha#7]
Request from upstream - @jkrenzer

Hi!

Thank you for the very helpful integration!

I wanted to suggest adding capabilities to share entities of the input_* domains.

Currently I run a setup where I employ several helpers like input_select to trigger automations or keep track of modes. Currently no config is generated for these entities as they are not mentioned in the conditionals in the file.

Broadcasting this entities in the discovery would make it much easier to employ these on external HA instances.

Thanks!

Jörn

**Comment by RogerSelwyn** [comment]
I think this can be done, just need to investigate.  @jkrenzer - Let me know what is the most important and I'll try that first.

**Comment by RogerSelwyn** [comment]
Just to add, this is a forked version which has had significant change to fix issues, with some additions.

**Comment by RogerSelwyn** [comment]
Looking at this it doesn't seem that HA MQTT supports input_select as such, but I think it would be possible to sync an `input_select.xxx` to `select.xxx` which HA does support. Entities that can be added directly are listed here - https://www.home-assistant.io/integrations/mqtt/

**Comment by jkrenzer** [comment]
> Looking at this it doesn't seem that HA MQTT supports input_select as such, but I think it would be possible to sync an `input_select.xxx` to `select.xxx` which HA does support. Entities that can be added directly are listed here - https://www.home-assistant.io/integrations/mqtt/

I'd say projecting input_select to select would be fine in most cases I guess. From the documentation it seems to hint at select being the foundation of input_select anyways. When you want to have two input_select synced between instances, it would mean to introduce two sync automations and two additional entities. But I don't know if there is a more elegant way around this right now. 🤔

**Comment by RogerSelwyn** [comment]
V1.2.0 adds support for input_select. If you can give that a go then I can see if there are any challenges before moving onto anything else.

https://github.com/RogerSelwyn/mqtt_discoverystream_ha/releases/tag/v1.2.0

**Comment by RogerSelwyn** [comment]
So far added select, button, number, text. In the process of adding boolean. Boolean creates a switch in the remote.

**Comment by jkrenzer** [comment]
Thank you very much. I am currently very busy, so I was not able to test yet. But I will as soon as I got some space to breath again.

**Comment by RogerSelwyn** [comment]
No worries. Adding all these has encouraged me to make really major changes to the codebase to make it simpler to extend. Consequently I've separated it from the original koying code base. I'm trying to add as many items as I can but since I don't have a fan or humidifier or lawnmower or etc, it's limited as to what I can add.

**Comment by RogerSelwyn** [comment]
I've added all the input entities apart from input_datetime since there is no equivalent for that the list supported by mqtt. It doesn't appear to be based on any other entity.

Consequently I'm going to close this request.
