### ISSUE TITLE
Hangs on master instance restart.

### ISSUE THREAD

**Issue by miguelangel-nubla** [RogerSelwyn/mqtt_discoverystream_ha#8]
This seems like a two sided problem.
When I restart the master instance the mqtt discovery topics with the data are not sent on startup, but, the slave still shows them as normal without marking them as unknown.
Then when I try to interact with the entities from the slave instance, the command topic is correctly sent to the mqtt broker but master ignores it.
This is solved as soon as I interact with the entity on the master, discovery and attributes are sent to the mqtt broker and commands received from the slave are executed correctly again.

Happening on HA 2024.3.0 and extension v0.11.05

**Comment by RogerSelwyn** [comment]
Yes, this is the way it works I’m afraid. The challenge is that many of the entities don’t exist when this integration starts up, so it is not possible to build the discovery topics for them. 

It might be possible to create a service that someone calls after a restart, to poll for all entities. Or potentially run a service after a set time. Not sure if there is an event that says HA is fully stated that could be listened for. 

To be honest I handle the problem by retaining the entries on my slave broker, so they are always there.

**Comment by RogerSelwyn** [comment]
Just to add, the slave is the core HA MQTT integration over which I have no control. If you have a problem with that, you need to take it up with the core team.

**Comment by Matsuo3rd** [comment]
> To be honest I handle the problem by retaining the entries on my slave broker, so they are always there.

Can you please elaborate on that? I am retaining messages sent to "command_topic" (from config field) but this does not seem to be enough to overcome HA restart issue. What needs to be retained exactly? Thanks.

**Comment by RogerSelwyn** [comment]
> > To be honest I handle the problem by retaining the entries on my slave broker, so they are always there.
> 
> Can you please elaborate on that? I am retaining messages sent to "command_topic" (from config field) but this does not seem to be enough to overcome HA restart issue. What needs to be retained exactly? Thanks.

You need to retain the items sent to your discovery_topic, those are what create the entities at the slave end. I wouldn't retain items sent to the command_topic, because that is a trigger for initiating something (e.g. turning a light on), which you wouldn't want to re-trigger just because your restarted your server.

I won't get to this until next week, but I'm mulling over mechanisms to handle this better.

**Comment by miguelangel-nubla** [comment]
As far as I understand the retain flag is set when the payload is sent to a specific topic, and only that payload is "retained", if you send new data without the retain flag set, nothing will be retained any longer and new clients will see nothing.
In order to retain certain topics `mqtt_discoverystream_ha` would have to set the retain flag every time it publishes to that topic, but I am not seeing that behavior nor a config option to enable that.

What am I missing? How are you achieving any kind of message retention in this scenario?

**Comment by Matsuo3rd** [comment]
Thanks. But retaining a message is done as an argument by the sender, in this case the "discovery_topic" publishing is done by your integration - but I don't see any option in the integration to do such thing.

**Comment by RogerSelwyn** [comment]
For me I set the retain flag on the bridge on the slave broker (I use EMQX), I don’t set anything on the master or in the message. If an empty message is sent to a topic, the topic is deleted, but you shouldn’t see empty messages from the integration.

**Comment by RogerSelwyn** [comment]
> Thanks. But retaining a message is done as an argument by the sender, in this case the "discovery_topic" publishing is done by your integration - but I don't see any option in the integration to do such thing.

As I’ve said above, all my retention is done by the bridge on my slave broker. I don’t require anything on the message.

**Comment by RogerSelwyn** [comment]
It’s possible the standard mosquito bridge that comes with HA can’t do this, I swapped to EMQX some time ago, it is way more informative than Mosquitto. 

I’ll aim to improve the mechanism in the coming weeks.

**Comment by miguelangel-nubla** [comment]
> It’s possible the standard mosquito bridge that comes with HA can’t do this

It definitely can't, ideally config options in `mqtt_discoverystream_ha` such as `retain_discovery: true` would make it interoperable with any MQTT server, and allow any slave restarting while the master is offline to "load" the entities correctly anyway.
Maybe not even an option is warranted and doing it by default for discovery topics make more sense. I can't think of a reason why anyone would want otherwise.

> Not sure if there is an event that says HA is fully stated that could be listened for.

[MQTT last will messages](https://www.home-assistant.io/integrations/mqtt/#birth-and-last-will-messages) seems like a good fit.
You can watch both `homeassistant/status` of the master and `homeassistant_slave/status` of the slave and re-build the discovery topics any time one changes and both of them contain `online`.
This in turn removes the need for any retain logic discussed above.

Building on top of that, it would be possible to set `availability_topic` for each discovery config of the entities to the master `homeassistant/status`, that way entities would automatically show as unavailable any time master is down.

**Comment by RogerSelwyn** [comment]
I personally I don't want to mandate a retain as standard, because then if someone removes an entity, they would have to manually go and delete it from the broker (which is what I have to do with my setup). If they stay on the broker permanently, the entities would always get re-created at the slaves.

The integration runs on the master HA instance (it isn't like an add-on that keeps running when HA is down), so it can't do anything when the HA instance is down, because it isn't running. Therefore it cannot monitor for online/offline/availability of the master.

It could possibly monitor for an LWT that appears on the MQTT, but I don't believe it will know whether the LWT is from a slave that is subscribed to integration delivered discoveries/states. I don't believe it has any knowledge of who the slaves are, or even if there are any at all. 

Bear in mind the only ongoing connection the integration has to the master MQTT broker is via a subscription for command responses (which if you are only syncing sensors, there would be none). The integration publishes messages to the master broker and subscribes to commands sent back to the master broker. Everything else is handled by the core MQTT integrations at master and slave.

So, I will look to add a service that can be called to re-run discovery. Then users can call that whenever they wish (whether triggered by an MQTT message, an event, time of day or anything else) via their automation platform of choice (personally I prefer Node Red because it is way more powerful than HA automation).

**Comment by miguelangel-nubla** [comment]
> If they stay on the broker permanently, the entities would always get re-created at the slaves.

I agree, retain is a nice workaround but would be a wrong implementation.


> The integration runs on the master HA instance (it isn't like an add-on that keeps running when HA is down), so it can't do anything when the HA instance is down, because it isn't running. Therefore it cannot monitor for online/offline/availability of the master.

Does not need to, only need to watch for online status of master, which happens **after** all the integrations have been loaded which solves:
> The challenge is that many of the entities don’t exist when this integration starts up

There is also a `homeassistant_started` [event](https://www.home-assistant.io/docs/configuration/events/#homeassistant_start-homeassistant_started) that is fired at the same time even when LWT is not configured in the MQTT integration.

Regarding slaves:
> I don't believe it has any knowledge of who the slaves are, or even if there are any at all.

In order for [mqtt discovery](https://www.home-assistant.io/integrations/mqtt/#mqtt-discovery) to work on the slave, `base_topic` on the integration must match the `discovery_prefix` on the slave mqtt integration, and by default `<discovery_prefix>/status` will be LWT for the slave which can be monitored from master just fine, re-sending discovery any time it receives an `online`

**Comment by RogerSelwyn** [comment]
The service will provide everything you need to be triggered based on your needs.

**Comment by RogerSelwyn** [comment]
> Does not need to, only need to watch for online status of master, which happens **after** all the integrations have been loaded which solves:

The integration already waits for the core MQTT to be online which is not necessarily before all other integrations are loaded, only before those that have MQTT as a dependency in their manifest (and to be honest I don’t think even that is sure). 

In the end we can argue about this all day. But a service is what I will endeavour to provide as and when I get a chance.

**Comment by RogerSelwyn** [comment]
I just had a look at the code. The retain bit is set on all messages sent by the integration which is replicated from the version I forked from. So the issue maybe that the core mqtt ignores the retained state messages and only acts on the new states being sent. 

I'd aim to write a service to run the discovery, plus publish current state.

**Comment by miguelangel-nubla** [comment]
> The retain bit is set on all messages sent by the integration

Well after that confirmation and still not seeing the messages retained in my mosquitto broker I found out about [max_queued_messages](https://mosquitto.org/man/mosquitto-conf-5.html) that defaults to 1000, which basically means a limit of 1000 retained messages. Changed it to 100000 in the addon, now topics retained as expected. (Upgrade to EMQX looking more enticing by the minute)


> In the end we can argue about this all day. But a service is what I will endeavour to provide as and when I get a chance.

I hope my comments aren't misconstrued as an argument. I am just trying to understand the decisions made in the code in order to get to a solution without reinventing the wheel.

In that same spirit I don't believe I explained myself here:

> > Does not need to, only need to watch for online status of master, which happens **after** all the integrations have been loaded which solves:
> 
> The integration already waits for the core MQTT to be online which is not necessarily before all other integrations are loaded, only before those that have MQTT as a dependency in their manifest (and to be honest I don’t think even that is sure).

I am talking about the online status of "master" HA core instance itself, not core MQTT integration.

HA sends the `online` payload to `homeassistant/status` MQTT topic (and the `homeassistant_started` event, not to confuse with `homeassistant_start` event) explicitly <ins>after</ins> it has finished loading *every* integration, and much later after core MQTT integration is online and connected to the MQTT broker.

Which I still think applies as the perfect time to run that potential new service.

**Comment by RogerSelwyn** [comment]
Have a look and see what I'm currently releasing meets your need

**Comment by RogerSelwyn** [comment]
OK. So this release adds a service that will re-publish all discovery messages and current states. This process is also called when `homeassistant_started` is posted on the event bus. It does not subscribe to LWT messages from the slave. You'll probably correctly me, but I think in a base setup they won't be visible to the master. I'll expand on why I think that.

In a base setup, where someone is using a separate base, discovery and command topic from the standard 'homeassistant` (to avoid loops in a two way scenario) , and include and entity (such as a switch) that has commands, you will likely need there subscriptions:

1. Slave subscribe to master for discovery topics - `master_topic_discovery` and rewrite two `homeassistant`
2. Slave subscribe to master for state topics - `master_topic`
3. Master subscribe to slave for command topics - `master_topic_command`

I think to get LWTs to the master, it would need a fourth subscription from master to slave on `homeassistant\state`, probably rewritten to something else `master_topic\state` so you knew where it came from.

It maybe I'm missing something here if this is wrong, but with the three subscriptions listed above I don't get an LWT back at the master when I reboot HA.

**Comment by miguelangel-nubla** [comment]
The version you just released is working great, I am no longer able to hang it by restarting.
Thank you.

Regarding LWTs from the slaves fourth subscription, yes, I see it the same way.
However, you can fully configure where slave HA puts LWTs, so I don't get why you would need to rewrite it to `master_topic\state`? Also wouldn't it be `slave_topic\state`?
Why would you need to know where it came from?

Allow me to explain how I use it, maybe we are talking about different scenarios:
I have two HA instances, one for private use and another one I share with neighbors for "public" use.
I use the same MQTT broker, each HA instance has its own MQTT logins and ACL.
- Private instance (Master) can readwrite topics under:
  - `homeassistant/#`
  - `homeassistant_public/#`
- Public instance (Slave) can readwrite topics under:
  - `homeassistant_public/#`

The extension on the master is configured as follows:
```
mqtt_discoverystream:
  base_topic: homeassistant_public
  publish_attributes: true
  publish_timestamps: true
  publish_discovery: true
  include:
    entities:
      - cover.gate_cars
      - switch.gate_pedestrian
```

In slave HA MQTT core integration, mqtt topic prefix is configured as `homeassistant_public` so discovery is working out of the box and LWTs are written by default on `homeassistant_public/status` where master can see them and act acordingly.

I don't use this with multiple slaves, which is a use case you seem to be referring to, but in that case I guess multiple slaves can be configured the same way under `homeassistant_public/` and everything work anyway? Don't matter where `homeassistant_public/status=online` comes from, just refresh discovery.

In my mind, if multiple slaves are needed, the best solution would be to run multiple instances of the integration, in order to have everything separated and be able to fully control which instances get access to which entities.
```
mqtt_discoverystream:
  public_1:
    base_topic: homeassistant_public_1
    publish_attributes: true
    publish_timestamps: true
    publish_discovery: true
    include:
      entities:
        - cover.gate_cars
  public_2:
    base_topic: homeassistant_public_2
    publish_attributes: true
    publish_timestamps: true
    publish_discovery: true
    include:
      entities:
        - switch.gate_pedestrian
```

**Comment by RogerSelwyn** [comment]
I suspect this works for you because you are using one broker. My scenario and what I get asked about often is a two site scenario, with sync of different entities in either direction. So site A is master syncing entities to site B slave, and site B master syncing entities to Site A slave. Each site has its own broker, so there is no visibility of topics across items apart from by bridge subscriptions.

Whilst you can configure where LWT is placed, that assumes you are using HA MQTT for nothing else that will expect the LWT is in a standard location. I'm not sure whether that is a problem or not, but I wouldn't want to just assume not.

**Comment by miguelangel-nubla** [comment]
Now I get what you mean with the subscription and rewriting.

In that case a fourth subscription from master to the slave LWT standard location, then adding config option `lwt_topic: wherever_slave_lwt/status` would be a valid solution?

**Comment by RogerSelwyn** [comment]
I’ll think on it

**Comment by Matsuo3rd** [comment]
I can report v0.12.00 solved my issue! Thank you! Much appreciated!

**Comment by RogerSelwyn** [comment]
> Now I get what you mean with the subscription and rewriting.
> 
> In that case a fourth subscription from master to the slave LWT standard location, then adding config option `lwt_topic: wherever_slave_lwt/status` would be a valid solution?

I've added a birth_topic option. No use having lwt because that is telling me the slave has gone offline which I can't do anything with. It will now re-run discovery and state publish when it sees and `online` message at the specified topic location.

I've also added some flow charts to try to clarify what is going on and when.

**Comment by miguelangel-nubla** [comment]
Just tested, working great.

Manually removed whole topic prefix, rebooted slave and discovery recreated on boot.

I guess retain is no longer needed, and removing it would make entities no longer exposed in `mqtt_discoverystream` disappear on the slaves as expected.

**Comment by RogerSelwyn** [comment]
I was considering that. Again, I’ll think on it.

**Comment by RogerSelwyn** [comment]
Basically I need to think about people who only have discovery/state publish and don't want the complexity of command/birth from slave to master. If there is no retain, then when they reboot slave, they will get nothing created.

There are only a few users of this fork of the integration, so I could force that they need to subscribe to birth messages (including me). Or I could set an option to turn off the retain (and add the subscribe for the birth). I know you don't need to do a subscription because you only have one broker, but I believe the majority are working a two site/broker solution.

**Comment by miguelangel-nubla** [comment]
I get that, but the options are either dangling old entities with retain on, or manual update required to upgrade.

- Retain ON:
  - Pros: Backwards compatibility, no changes needed.
  - Cons: Dangling old entities forever available.
- Retain OFF:
  - Pros: Entities up to date, able to remove and rename entities without drama.
  - Cons: Manual configuration update required.

Also isn't master already subscribed to slave command topic in your scenario?
Specifying `birth_topic: command_topic/status` on master and configure mqtt birth or automation to write there on slave boot would be enough.

Then you can effectively call master's `publish_discovery_state` service from slave on demand.

**Comment by miguelangel-nubla** [comment]
I am not seeing the flexibility to avoid a risk, every usage case has the option to comply without drawback, only benefit. In the worst case scenario using a automation would be risk free.

The perceived time saved by "not touching it", goes out the window the first time you have to put the time to solve a issue caused by a entity rename/deletion/update, talking from experience.

**Comment by miguelangel-nubla** [comment]
You are right I personally would never even consider option 2, I like to simplify things.

Good luck with the Pi, been there, not missing it.

I [migrated back](https://community.home-assistant.io/t/migrate-back-from-mariadb-to-the-default-sqlite/604278) to SQLite a few days ago, performance is anecdotally better and I suppose would not be a issue with the Pi5

**Comment by RogerSelwyn** [comment]
> I [migrated back](https://community.home-assistant.io/t/migrate-back-from-mariadb-to-the-default-sqlite/604278) to SQLite a few days ago, performance is anecdotally better and I suppose would not be a issue with the Pi5

I'm considering that as well

**Comment by RogerSelwyn** [comment]
> You are right I personally would never even consider option 2, I like to simplify things.

Looks like I'm going to have to go with Option 2. 

In testing on my setup, when I don't retain messages and do a restart of my slave instance (which is actually my core HA running on Mac M1 Mini, not a Pi), all the MQTT synced entities are not 're-discovered'. 

I can see that the MQTT discovery/state messages were resent by the master (the Pi), and available on the slave broker, but I guess the slave core MQTT integration isn't quite ready to receive them yet.

 If I re-run the publish (using the service) on the master, the entities are correctly re-discovered on the slave.

**Comment by miguelangel-nubla** [comment]
> but I guess the slave core MQTT integration isn't quite ready to receive them yet.

That sounds strange, are you using slave mqtt core for birth message or automation?

I cannot reproduce it in my setup, even manually creating a discovery topic `config` with no retain, for a ghost entity, gets detected instantly every time after slave ha boot.

Are you sure the `online` is coming back to the master correctly? It is effectively a remote control for running the service on the master, does not make sense the result is different by changing the "caller".

**Comment by RogerSelwyn** [comment]
I'm using the birth message from slave to master (which will happen on EVENT_HA_STARTED, which triggers the republish. But when I look all my entities from the master are unavailable. 

Just trying to debug core MQTT code to see if something its going on there.

**Comment by miguelangel-nubla** [comment]
I use this automation on the slave with birth and last will disabled.
```
alias: Discovery test
description: ""
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: mqtt.publish
    metadata: {}
    data:
      payload: online
      topic: homeassistant_public/status
mode: single
```

Triggering it manually after boot also works as expected.

**Comment by RogerSelwyn** [comment]
I think it might be that it is creating the entity, but is trying to process the state message before the entity is created.

**Comment by RogerSelwyn** [comment]
So... if I add a 5 second delay after publishing all discoveries, before publishing any statuses, then it works fine. Why it works for you, I don't know.

**Comment by miguelangel-nubla** [comment]
I am seeing the same behavior you are seeing if I create the topics from slave ha directly. Seems a race condition.

Without retain, order matters.
1. Discovery topic received by core mqtt
2. Discovery data processed by ha
3. Subscription to state, availability, etc topics made.
4. Starts to process new messaged received to those topics

If all topics are sent at the same time, a race condition occurs and data arrived to slave before point 3 is never seen.

I have a very lightweight slave ha instance on a vm host with powerfull hardware, maybe that is why is not always happening to me.

So the solution is either the delay (which would be arbitrary or even not enough on certain circumstances) or maintain retain in all messages except the `discovery/config` one.

**Comment by RogerSelwyn** [comment]
The problem occurs on my Mac Mini M1 (which is way overpowered for the job), and on my Pi4B. When I add a 5 second pause between discovery and state publication it seems to be fine. Flowchart on home of Github shows the flow.

**Comment by miguelangel-nubla** [comment]
Does this automation work for you?

```
alias: Discovery test 2
description: ""
trigger: []
condition: []
action:
  - variables:
      name: ghost_10
      discovery_topic: homeassistant_public
  - service: mqtt.publish
    data:
      topic: "{{ discovery_topic }}/switch/{{ name }}/state"
      retain: true
      payload: "off"
  - service: mqtt.publish
    data:
      topic: "{{ discovery_topic }}/switch/{{ name }}/attributes"
      retain: true
      payload: |-
        {
          "icon": "mdi:door-closed-lock",
          "friendly_name": "{{ name }} Entity"
        }
  - service: mqtt.publish
    data:
      topic: "{{ discovery_topic }}/switch/{{ name }}/availability"
      retain: true
      payload: online
  - service: mqtt.publish
    data:
      topic: "{{ discovery_topic }}/switch/{{ name }}/config"
      payload: |-
        {
          "uniq_id": "mqtt_switch.{{ name }}",
          "obj_id": "{{ name }}",
          "stat_t": "{{ discovery_topic }}/switch/{{ name }}/state",
          "json_attr_t": "{{ discovery_topic }}/switch/{{ name }}/attributes",
          "avty_t": "{{ discovery_topic }}/switch/{{ name }}/availability",
          "name": "{{ name }} Entity",
          "pl_off": "off",
          "pl_on": "on",
          "cmd_t": "{{ discovery_topic }}/switch/{{ name }}/set"
        }
mode: single

```

**Comment by RogerSelwyn** [comment]
Sorry, I use Node Red for automation, I'm afraid HA automation is YAML and doesn't deal with the complexity of what I automate.

**Comment by miguelangel-nubla** [comment]
I mean for testing only. That one has retain on everything but discovery. If that works fine on your setup then it is a possible solution.

**Comment by RogerSelwyn** [comment]
I know, but I'd then have to enable Automation. If you have an idea to test, probably easier for me to test in the integration code.

If it is something you are having a problem with, I can fairly easily enable automation on my dev site. What is the problem?

**Comment by miguelangel-nubla** [comment]
Testing in the integration code would be as easy as set retain on `discovery/config` message to always false, and true in all the other messages by default.

**Comment by miguelangel-nubla** [comment]
Meaning force retain off [here ](https://github.com/RogerSelwyn/mqtt_discoverystream_ha/blob/ecde8334dd562d6a6b64f3a0b0dc5d45dc61435f/custom_components/mqtt_discoverystream/discovery.py#L127) while global retain is on.

**Comment by RogerSelwyn** [comment]
What are you trying to achieve?

**Comment by RogerSelwyn** [comment]
By the way it is working fine for me with latest version I posted.

**Comment by miguelangel-nubla** [comment]
I am trying to avoid the issue happening without the 5 sec delay, any other way than adding a delay.

A delay is not guaranteed to work since you can only control the send timing, not the receive timing.
Some examples where it will fail:
- If the network connection between master and slave is dropped before the 5 sec delay, and then recovered, all the topics will arrive at the same time at the slave.
- Slow/partially hung slave ha instances: messages will be added to the queue, then later received at the same time.

**Comment by RogerSelwyn** [comment]
Mate. If you don’t like it raise a PR for something that works for you. There are so many ifs and maybes in here. Yesterday you didn’t want any retains, now you will accept them.  And yes I know this may fail very occasionally, I’ll deal with that over it failing every time. 

Sorry, I’ve had a bad day and I’ve still got to cook for the family.

**Comment by RogerSelwyn** [comment]
> Does this automation work for you?
> 
> ```
> alias: Discovery test 2
> description: ""
> trigger: []
> condition: []
> action:
>   - variables:
>       name: ghost_10
>       discovery_topic: homeassistant_public
>   - service: mqtt.publish
>     data:
>       topic: "{{ discovery_topic }}/switch/{{ name }}/state"
>       retain: true
>       payload: "off"
>   - service: mqtt.publish
>     data:
>       topic: "{{ discovery_topic }}/switch/{{ name }}/attributes"
>       retain: true
>       payload: |-
>         {
>           "icon": "mdi:door-closed-lock",
>           "friendly_name": "{{ name }} Entity"
>         }
>   - service: mqtt.publish
>     data:
>       topic: "{{ discovery_topic }}/switch/{{ name }}/availability"
>       retain: true
>       payload: online
>   - service: mqtt.publish
>     data:
>       topic: "{{ discovery_topic }}/switch/{{ name }}/config"
>       payload: |-
>         {
>           "uniq_id": "mqtt_switch.{{ name }}",
>           "obj_id": "{{ name }}",
>           "stat_t": "{{ discovery_topic }}/switch/{{ name }}/state",
>           "json_attr_t": "{{ discovery_topic }}/switch/{{ name }}/attributes",
>           "avty_t": "{{ discovery_topic }}/switch/{{ name }}/availability",
>           "name": "{{ name }} Entity",
>           "pl_off": "off",
>           "pl_on": "on",
>           "cmd_t": "{{ discovery_topic }}/switch/{{ name }}/set"
>         }
> mode: single
> ```

This allows the entity to be created and state applied correctly. This is kind of what you would expect because the state is retained on the broker ready for when the subscription happens.

This has the potential to leave unrequired state messages on the broker, related to entities that have now been deleted. I actually prefer this less than retaining everything.

**Comment by miguelangel-nubla** [comment]
Then I see no better way to auto clean old entities.
The current solution does work for me. Thank you.

-----

Now that birth and last will logic is implemented, have you consider using the master's LWT topic as `availability_topic` for the entities? That way when master is down, entities show up as unavailable on slave.

An idea to keep current functionality in the case master is up and entity is unavailable on master:
- When entity unavailable, delete `availability_topic` and send `offline` to `availability` topic, 
- When available again, delete `availability` instead of setting it to `online`, and set `availability_topic` again.

That is of course if mqtt core behavior does not have more surprises handling that.

**Comment by RogerSelwyn** [comment]
I'm away for a week, so this will likely only get looked at next week-end at the earliest.

**Comment by RogerSelwyn** [comment]
Just as a note, I added a new entity to sync to one of my masters (bear in mind I have a two way sync) and then restarted that master. On the slave, the entity was created but with no status. I suspect there is a more general problem of race condition between entity creation and entity state setting. I'll continue to think on the matter, but can't do any development until next week.

(I did post a new release because of an issue with that new entity, but I could see from HA core what the issue was and what I needed to do to fix it - reverting code).

**Comment by RogerSelwyn** [comment]
I have discovered that you can have an array of topic to monitor for availability, and take the availability for `all`, `any` or `latest`. Latest is the default which seems appropriate. Just working through logic in my head at the moment.

**Comment by miguelangel-nubla** [comment]
Sounds really useful for this usecase, did not know that was an option. Can you elaborate why you are considering latest the most appropiate?

**Comment by miguelangel-nubla** [comment]
Ok, I see.
The only thing I can think of that could be considered a concern, albeit a very minor one is: 
In the `latest` case, master HA `online` makes all entities available until the 5 second delay to publish states (and I guess availability topic for the entity too for the same reasons) is over, and therefore entities not available "anytime today" be briefly seen as available on the slave. The result of this would be that automations on the slave based on that entity are broken.

Did you find any potential drawbacks to `all` ?

**Comment by RogerSelwyn** [comment]
No drawbacks, it was just the default. I'm changing the delay to 1 second at the moment. Just working things through

**Comment by RogerSelwyn** [comment]
I'll probably change it to All by the way.

**Comment by RogerSelwyn** [comment]
The drawback of `all`.... `homeassistant\status` isn't retained on the broker, and whilst I could force retention as part of my bridging that won't work for you. Also I don't work to start fiddling with core mqtt messages, so I can't see how to get it to republish the fact that it is online. Consequently slave is sitting there waiting for all items to be online, and HA never is.

So I'm just testing, but I'm going to change it to `latest`.

**Comment by miguelangel-nubla** [comment]
Just testing v1.1.1, I don't see any better options either. Working as expected.

Only issue I can find is that master's LWT `offline` is set on the broker on mqtt core disconnection, much later than when homeassistant is manually stopped/restarted.
(In case other thing happens, ha crashes or mqtt connection drops it is immediate and work as expected.)

I am thinking watching for event [`homeassistant_stop`](https://www.home-assistant.io/docs/configuration/events/#homeassistant_stop-homeassistant_final_write-homeassistant_close) to set every entity availability to `offline` as a solution?

Similar to startup logic with `homeassistant_start` vs `homeassistant_started` event, my understanding is that when `homeassistant_stop` is fired, the extension is still able to set the availability topics for a few moments.

**Comment by RogerSelwyn** [comment]
I'll take a look

**Comment by RogerSelwyn** [comment]
> Just testing v1.1.1, I don't see any better options either. Working as expected.
> 
> Only issue I can find is that master's LWT `offline` is set on the broker on mqtt core disconnection, much later than when homeassistant is manually stopped/restarted. (In case other thing happens, ha crashes or mqtt connection drops it is immediate and work as expected.)
> 
> I am thinking watching for event [`homeassistant_stop`](https://www.home-assistant.io/docs/configuration/events/#homeassistant_stop-homeassistant_final_write-homeassistant_close) to set every entity availability to `offline` as a solution?
> 
> Similar to startup logic with `homeassistant_start` vs `homeassistant_started` event, my understanding is that when `homeassistant_stop` is fired, the extension is still able to set the availability topics for a few moments. I have three entities setup to sync in my dev.

Coded that up but it doesn't work. The MQTTDS integration uses the core MQTT integration to send to the broker (no I'm not going to code an MQTT client just for this), but that then gets no ack from the broker when I try to send an unavailable message (my test broker is running on another server). Debug added to give visibility.


```
2024-03-26 13:15:36.758 INFO (MainThread) [custom_components.mqtt_discoverystream.publisher] shutdown
2024-03-26 13:15:36.758 INFO (MainThread) [custom_components.mqtt_discoverystream.publisher] light.bedside_light
2024-03-26 13:15:47.439 WARNING (MainThread) [homeassistant.components.mqtt.client] No ACK from MQTT server in 10 seconds (mid: 22)
2024-03-26 13:15:47.439 INFO (MainThread) [custom_components.mqtt_discoverystream.publisher] switch.living_room_hue_motion_motion
2024-03-26 13:15:57.472 WARNING (MainThread) [homeassistant.components.mqtt.client] No ACK from MQTT server in 10 seconds (mid: 23)
2024-03-26 13:15:57.473 INFO (MainThread) [custom_components.mqtt_discoverystream.publisher] climate.bedroom_3
2024-03-26 13:16:07.485 WARNING (MainThread) [homeassistant.components.mqtt.client] No ACK from MQTT server in 10 seconds (mid: 24)
```

**Comment by miguelangel-nubla** [comment]
I don't get why it does work with a ha automation using `mqtt.publish` service then, should go similar route.

Seems `mqtt.publish` calls [async_publish](https://github.com/home-assistant/core/blob/53944b260cacb91742f2b62438ef64ced52da81f/homeassistant/components/mqtt/client.py#L99) directly.

Maybe QoS plays a role?
Does this kind of automation work on your setup? It does work correctly on mine.
```
alias: ha slave offline entities on shutdown
description: ""
trigger:
  - platform: homeassistant
    event: shutdown
condition: []
action:
  - service: mqtt.publish
    metadata: {}
    data:
      topic: homeassistant/status
      payload: offline
mode: single
```

**Comment by RogerSelwyn** [comment]
Changing to QoS 0 seems to do the trick. Fire it and hope it gets through.

**Comment by RogerSelwyn** [comment]
They v1.1.2

**Comment by miguelangel-nubla** [comment]
It is working great on my side.

Also just to note this does not happen:
> In the `latest` case, master HA `online` makes all entities available until the 5 second delay to publish states (and I guess availability topic for the entity too for the same reasons) is over, and therefore entities not available "anytime today" be briefly seen as available on the slave.

Seems in a retain-disabled scenario, online comes before discovery, so not an issue at all.

Thank you very much for all the solutions.
This would be a great addition to homeassistant core.

**Comment by RogerSelwyn** [comment]
I'm hoping this fix in 2024.5.3 will fix the race issue where entity update was happening before entity creation was complete. I'll test over the next few days and see if the delay can be taken out.

https://github.com/home-assistant/core/pull/117105

**Comment by miguelangel-nubla** [comment]
Im away from home, will check in my environment as soon as I get back nest week.

**Comment by RogerSelwyn** [comment]
> Im away from home, will check in my environment as soon as I get back nest week.

Nope, it is still a problem
